<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_bef-registrant-details',
		'title' => 'BEF Registrant Details',
		'fields' => array (
			array (
				'key' => 'field_5769cd14251d9',
				'label' => 'Business Phone',
				'name' => 'bef_business_phone',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5786c77b4ea92',
				'label' => 'Who is Your Coach?',
				'name' => 'who_is_your_coach',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c55c1ece87',
				'label' => 'Package 1 Quantity',
				'name' => 'package_1_quantity',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c54a689e39',
				'label' => 'Package 1 Names',
				'name' => 'package_1_names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c55db3271f',
				'label' => 'Package 2 Quantity',
				'name' => 'package_2_quantity',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c54e16da77',
				'label' => 'Package 2 Names',
				'name' => 'package_2_names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c55f1f8005',
				'label' => 'Package 3 Quantity',
				'name' => 'package_3_quantity',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c54f230b0b',
				'label' => 'Package 3 Names',
				'name' => 'package_3_names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c56052f615',
				'label' => 'Package 4 Quantity',
				'name' => 'package_4_quantity',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c5500d5716',
				'label' => 'Package 4 Names',
				'name' => 'package_4_names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c56181b5fc',
				'label' => 'Package 5 Quantity',
				'name' => 'package_5_quantity',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c551ee7fd4',
				'label' => 'Package 5 Names',
				'name' => 'package_5_names',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c557c2f805',
				'label' => 'Total Amount',
				'name' => 'total_amount',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c565c8cf8a',
				'label' => 'Billing Address 1',
				'name' => 'billing_address_1',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_576c56834c170',
				'label' => 'Billing Address 2',
				'name' => 'billing_address_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_576c56a05e4b8',
				'label' => 'Billing City',
				'name' => 'billing_city',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_576c56bfe23ff',
				'label' => 'Billing State',
				'name' => 'billing_state',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_576c56d77e610',
				'label' => 'Credit Card Last Four',
				'name' => 'credit_card_last_four',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_576c56f5085d1',
				'label' => 'Split Payment',
				'name' => 'split_payment',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_576c5722062c0',
				'label' => 'Payment Status',
				'name' => 'payment_status',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57870fb3f47bf',
				'label' => 'Package 1 Shirt Sizes',
				'name' => 'package_1_shirt_sizes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ab4c3122a',
				'label' => 'Package 2 Shirt Sizes',
				'name' => 'package_2_shirt_sizes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ab613122b',
				'label' => 'Package 3 Shirt Sizes',
				'name' => 'package_3_shirt_sizes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ab633122c',
				'label' => 'Package 4 Shirt Sizes',
				'name' => 'package_4_shirt_sizes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ab643122d',
				'label' => 'Package 5 Shirt Sizes',
				'name' => 'package_5_shirt_sizes',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ac60095a8',
				'label' => 'Package 1 Diets',
				'name' => 'package_1_diets',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ac861889b',
				'label' => 'Package 2 Diets',
				'name' => 'package_2_diets',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ac871889c',
				'label' => 'Package 3 Diets',
				'name' => 'package_3_diets',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ac891889d',
				'label' => 'Package 4 Diets',
				'name' => 'package_4_diets',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5787ac8a1889e',
				'label' => 'Package 5 Diets',
				'name' => 'package_5_diets',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'bef_registrant',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}
